\subsection{Reading \TESS output}\label{sec:TESS_data}

Needs to be written ...

First, load the \TESS package.
<<load-TESS>>=
library(TESS)
@

For some of our plotting, we need the speciation times.
So we extract these from the tree.
<<TESS-read-times>>=
btimes <- sort( as.numeric( branching.times( tree ) ) )
max_t <- max(btimes)
@

<<TESS-analysis, echo=TRUE, cache=TRUE>>=
tess.analysis(tree,
              empiricalHyperPriors = TRUE,
              samplingProbability = 1.0,
              numExpectedRateChanges = 2,
              MAX_ITERATIONS = 100000,
              MAX_TIME = 2*60*60,
              MIN_ESS = 625,
              dir = "primates_comet")
@

<<TESS-output, echo=TRUE, cache=TRUE>>=
tess.output <- tess.process.output("primates_comet",
                              numExpectedRateChanges = 2)
@

<<TESS-compute-median, cache=TRUE>>=
est_speciation <- apply(tess.output[["speciation rates"]],
                        2,quantile,prob=0.5)
est_extinction <- apply(tess.output[["extinction rates"]],
                        2,quantile,prob=0.5)
@

<<TESS-functions, cache=TRUE>>=
lambda <- approxfun( tess.output[["intervals"]],
                     c(est_speciation[1],est_speciation) )
mu <- approxfun(     tess.output[["intervals"]],
                     c(est_extinction[1],est_extinction) )
@
Finally, let's have a look at the estimated rate functions.
<<TESS-plot-functions, fig.height=4, fig.width=4, fig.align="center", fig.cap="Estimated speciation and extinction rates using TESS on the primates phylogeny of Springer et al. (2012).">>=
ylim <- c( min(0,est_speciation,est_extinction),
           max(est_speciation,est_extinction))

curve( lambda, xlim=c(max_t, 0), lwd=2, lty=1, col="blue",
       ylim=ylim, main="Primates", xlab="time", ylab="rate",
       cex.main=1.5, cex.lab=1.5 )
curve( mu, add=TRUE, lwd=2, lty=1, col="red" )
legend("bottomleft",legend=c("speciation","extinction"),
       col=c("blue","red"), lty=c(1,1), cex=1.2)
@

For a later use in the tutorial where we want to compare the estimates between different software, we are going to store the rate functions.
<<TESS-rates, cache=TRUE>>=
lambda.TESS <- lambda
mu.TESS     <- mu
@
You could now skip over the next software section and estimate the entire congruence class for these estimated speciation and extinction rates.